language: c
compiler:
    - gcc
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: ""

addons:
  coverity_scan:
    project:
      name: "Comcast/parodus2ccsp"
      description: " Webpa client to communicate with parodus in RDK environment. "
    notification_email: weston_schmidt@alumni.purdue.edu
    build_command_prepend: "mkdir coverity_build && cd coverity_build && cmake .."
    build_command:   "make"
    branch_pattern: coverity_scan

before_install:
    - sudo pip install codecov

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq libcunit1 libcunit1-dev lcov libcurl4-openssl-dev
    - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
    - sudo apt-get update
    - sudo apt-get -y install openssl libexpat1-dev
    - openssl version -a

script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTING:BOOL=true
    - sudo make
    - make test

after_success:
    - codecov
